logging:
  level:
    ROOT: info
    org.hibernate.SQL: INFO
    fr.codecake.airbnbcloneback: INFO

spring:
  datasource:
    # url: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
    url: jdbc:postgresql://dpg-d13ecuruibrs7385jdug-a.oregon-postgres.render.com/airbnbclonedb_t355
    username: ramzi
    password: 5vQkyJYVxGU919KhegjTjTrWPS8zDL30
  jpa:
    properties:
      hibernate:
        default_schema: public
  liquibase:
    contexts: prod
    default-schema: public
