logging:
  level:
    ROOT: info
    org.hibernate.SQL: INFO
    fr.codecake.airbnbcloneback: INFO

spring:
  datasource:
    # url: jdbc:postgresql://${POSTGRES_URL}:5432/${POSTGRES_DB}
    url: jdbc:postgresql://dpg-d1506bh5pdvs739d0rq0-a.frankfurt-postgres.render.com/myvoyagedb
    username: myvoyagedb_user
    password: hG0JqAIz0cNJvfevj4AUZCYoOTFKouQN
  jpa:
    properties:
      hibernate:
        default_schema: public
  liquibase:
    contexts: prod
    default-schema: public
